Add appropriate script to handle tang server healthiness

diff --git a/test_containers/fedora_tang_server/tangd-health-check b/test_containers/fedora_tang_server/tangd-health-check
--- a/test_containers/fedora_tang_server/tangd-health-check
+++ b/test_containers/fedora_tang_server/tangd-health-check
@@ -1,8 +1,8 @@
 #!/bin/sh -eu
 # vim: set ts=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
 #
-# Copyright (c) 2021 Red Hat, Inc.
-# Author: Sergio Arroutbi <sarroutb@redhat.com>
+# Copyright (c) 2020 Red Hat, Inc.
+# Author: Sergio Correia <scorreia@redhat.com>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -17,5 +17,36 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-### This is a very dump test to check for healthiness with no checks
+export PORT="${PORT:-80}"
+
+die() {
+    echo "${0}: ${1} (port: ${PORT})" >&2
+    exit 1
+}
+
+# Get the advertisement.
+jws="$(curl -sfg "http://localhost:${PORT}/adv")" \
+       || die "Error downloading advertisement"
+
+# Sanity check the advertisement.
+jwks="$(jose fmt --json="${jws}" --object --get payload --string \
+        --b64load --object --get keys --array --unwind --output=-)" \
+        || die "Advertisement is malformed"
+
+# Check validity.
+printf %s "${jwks}" \
+    | jose jwk use --input=- --required --use=verify --output=/dev/null \
+    || die "Advertisement is missing signatures"
+
+# Check for key derivation key.
+enc="$(printf %s "${jwks}" \
+       | jose jwk use --input=- --required --use=deriveKey --output=-)" \
+       || die "Key derivation key not available"
+
+# Check for exchange keys.
+jose fmt --json "${enc}" --object --get keys --array \
+    || enc="$(printf {keys: [%s]} "${enc}")"
+jose fmt --json="${enc}" --object --get keys --array --foreach=/dev/null \
+    || die "No exchange keys found"
+
 echo "ok"
